import type { IncomingMessage, ServerResponse } from "node:http";
import type { OpenClawPluginApi } from "openclaw/plugin-sdk";
import { listEnabledFeishuAccounts, resolveFeishuAccount } from "./accounts.js";
import { createFeishuClient } from "./client.js";
import type { FeishuConfig } from "./types.js";
import {
  buildAuthUrl,
  exchangeCodeForToken,
  persistUserToken,
  createPendingAuth,
  consumePendingAuth,
  loadUserToken,
} from "./user-auth.js";

function getFeishuConfig(api: OpenClawPluginApi): FeishuConfig | null {
  return (api.config?.channels?.feishu as FeishuConfig | undefined) ?? null;
}

/**
 * Register the OAuth callback HTTP route and `/feishu-auth` command.
 */
export function registerFeishuOAuth(api: OpenClawPluginApi): void {
  // ── HTTP callback route ──
  api.registerHttpRoute({
    path: "/plugins/feishu/oauth/callback",
    auth: "plugin",
    async handler(req: IncomingMessage, res: ServerResponse) {
      const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);
      const code = url.searchParams.get("code");
      const state = url.searchParams.get("state");

      if (!code || !state) {
        res.writeHead(400, { "Content-Type": "text/html; charset=utf-8" });
        res.end("<h1>Missing code or state parameter</h1>");
        return;
      }

      const accountId = consumePendingAuth(state);
      if (!accountId) {
        res.writeHead(400, { "Content-Type": "text/html; charset=utf-8" });
        res.end(
          "<h1>Invalid or expired authorization state</h1>" +
            "<p>The <code>state</code> parameter does not match any pending authorization.</p>" +
            "<p>This usually means the link was not generated by the <code>/feishu-auth</code> command, " +
            "or the authorization took longer than 10 minutes.</p>" +
            "<p><b>Fix:</b> Type <code>/feishu-auth</code> in the chat to get a valid authorization link, " +
            "then click it and authorize within 10 minutes.</p>",
        );
        return;
      }

      try {
        const account = resolveFeishuAccount({ cfg: api.config, accountId });
        const client = createFeishuClient(account);
        const token = await exchangeCodeForToken(client, code);
        persistUserToken(accountId, token);

        res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
        res.end(
          `<h1>Feishu OAuth Authorized</h1>` +
            `<p>Account: <b>${accountId}</b></p>` +
            `<p>User: <b>${token.openId}</b></p>` +
            `<p>You can close this window and return to OpenClaw.</p>`,
        );
        api.logger.info(
          `Feishu OAuth: user token obtained for account "${accountId}" (openId=${token.openId})`,
        );
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        api.logger.error(`Feishu OAuth callback error: ${msg}`);
        res.writeHead(500, { "Content-Type": "text/html; charset=utf-8" });
        res.end(`<h1>Authorization Failed</h1><p>${escapeHtml(msg)}</p>`);
      }
    },
  });

  // ── /feishu-auth command ──
  api.registerCommand({
    name: "feishu-auth",
    description: "Authorize Feishu user access (OAuth) for user-level APIs like task list",
    acceptsArgs: true,
    requireAuth: true,
    handler(ctx) {
      const feishuCfg = getFeishuConfig(api);
      if (!feishuCfg) {
        return { text: "Feishu channel is not configured." };
      }

      const accountId = ctx.accountId ?? "default";
      const account = resolveFeishuAccount({ cfg: api.config, accountId });
      if (!account.appId) {
        return { text: `Feishu account "${accountId}" has no appId configured.` };
      }

      // Check existing token
      const existing = loadUserToken(accountId);
      if (existing && existing.expiresAt > Date.now()) {
        if (ctx.args?.trim() !== "force") {
          return {
            text:
              `User token for account "${accountId}" is still valid (openId=${existing.openId}).\n` +
              `Run \`/feishu-auth force\` to re-authorize.`,
          };
        }
      }

      const callbackUrl =
        feishuCfg.oauthCallbackUrl ?? `http://localhost:18789/plugins/feishu/oauth/callback`;

      const state = createPendingAuth(accountId);
      const authUrl = buildAuthUrl({
        appId: account.appId,
        redirectUri: callbackUrl,
        state,
        domain: typeof account.domain === "string" ? account.domain : undefined,
      });

      return {
        text:
          `Please open this link to authorize Feishu user access:\n\n${authUrl}\n\n` +
          `The authorization link expires in 10 minutes.`,
      };
    },
  });
}

/**
 * Log user token status for each enabled account on startup.
 * Tokens are loaded from disk on demand (no SDK cache to warm up).
 */
export function logUserTokenStatus(api: OpenClawPluginApi): void {
  if (!api.config) return;
  const accounts = listEnabledFeishuAccounts(api.config);
  for (const account of accounts) {
    const token = loadUserToken(account.accountId);
    if (token) {
      const valid = token.expiresAt > Date.now();
      api.logger.info(
        `Feishu OAuth: account "${account.accountId}" has persisted user token ` +
          `(openId=${token.openId}, ${valid ? "valid" : "expired"})`,
      );
    }
  }
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
